### ISSUE TITLE
请教大佬

### ISSUE THREAD

**Issue by 0oOGEM** [yeyupiaoling/VoiceprintRecognition-Pytorch#26]
"D:\Program Files (x86)\Python\python.exe" E:/0,SHARED/WEB/VoiceprintRecognition-Pytorch-master/infer_recognition.py
Traceback (most recent call last):
  File "E:/0,SHARED/WEB/VoiceprintRecognition-Pytorch-master/infer_recognition.py", line 10, in <module>
    from data_utils.reader import load_audio, CustomDataset
  File "E:\0,SHARED\WEB\VoiceprintRecognition-Pytorch-master\data_utils\reader.py", line 11, in <module>
    import librosa
  File "D:\Program Files (x86)\Python\lib\site-packages\librosa\__init__.py", line 209, in <module>
    from . import core
  File "D:\Program Files (x86)\Python\lib\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "D:\Program Files (x86)\Python\lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "D:\Program Files (x86)\Python\lib\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "D:\Program Files (x86)\Python\lib\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "D:\Program Files (x86)\Python\lib\site-packages\librosa\util\utils.py", line 5, in <module>
    import scipy.ndimage
  File "D:\Program Files (x86)\Python\lib\site-packages\scipy\__init__.py", line 119, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "D:\Program Files (x86)\Python\lib\site-packages\scipy\_lib\_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: DLL load failed: 找不到指定的模块。

为什么我所有的第三方库都安装好了，项目是下载你的，一运行就会报错。

**Comment by MTCH77** [comment]
librosa库出现问题，我记得有个方法是重新装librosa0.6.0版本和numba0.48.0版本就行了
