### ISSUE TITLE
using ‘TripletAngularMarginLoss’ loss function will cause an issue about data dimension：RuntimeError: shape '[64, -1]' is invalid for input of size 250

### ISSUE THREAD

**Issue by Jotakak-yu** [yeyupiaoling/VoiceprintRecognition-Pytorch#67]
完整的报错信息如下：
```
Traceback (most recent call last):
  File "train.py", line 22, in <module>
    trainer.train(save_model_path=args.save_model_path,
  File "VoiceprintRecognition-Pytorch/mvector/trainer.py", line 599, in train
    self.__train_epoch(epoch_id=epoch_id, save_model_path=save_model_path, local_rank=local_rank,
  File "VoiceprintRecognition-Pytorch/mvector/trainer.py", line 483, in __train_epoch
    los = self.loss(outputs, label)
  File "/home/panjianan/anaconda3/envs/pt113cu116/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "VoiceprintRecognition-Pytorch/mvector/models/loss.py", line 309, in forward
    dist_ap = dist[is_pos].view(bs, -1).min(dim=1, keepdim=True)[0]
RuntimeError: shape '[64, -1]' is invalid for input of size 250

```

**Comment by yeyupiaoling** [comment]
@Jotakak-yu 你用的是什么模型？用什么预处理方式？

**Comment by Jotakak-yu** [comment]
> @Jotakak-yu 你用的是什么模型？用什么预处理方式？

模型是cam++，预处理方式fbank，参数默认

**Comment by Jotakak-yu** [comment]
@yeyupiaoling 大佬有空可以麻烦看一下吗？感谢！

**Comment by yeyupiaoling** [comment]
is_use_pksampler: True
在配置文件里面设置这个为。另外保证你代码是新的。

**Comment by Jotakak-yu** [comment]
> is_use_pksampler: True 在配置文件里面设置这个为。另外保证你代码是新的。

解决了，我换到develop分支之后就可以了
